name: Azure WSL stop
description: 'Deallocate an Azure VM.'

inputs:
  az_name:
    description: Name of the Azure VM to run on
    required: true
  az_resource_group:
    description: Name of the Azure resource group to run on
    required: true
  az_creds:
    description: Credentials to use for Azure
    required: true

runs:
  using: 'composite'
  steps:
    # - uses: azure/login@v1
    #   with:
    #     creds: ${{ inputs.az_creds }}
    # - name: Deallocate the Runner
    #   shell: bash
    #   run: |
    #     az vm deallocate --name ${{ inputs.az_name }} --resource-group ${{ inputs.az_resource_group }}
    - name: Deallocate the Runner
      shell: bash
      run: |
        echo "Done"


branding:
  icon: 'arrow-down-circle'
  color: 'orange'